syntax = "proto3";

package subscription;

option go_package = "grpc/gen;subscription";

service SubscriptionService {
    rpc ListSubscriptions (ListSubscriptionsRequest) returns (ListSubscriptionsResponse);
}

message Subscription {
    string service_name = 1;
    int64 price = 2;
    string user_uuid = 3;
    string start_date = 4;
    string stop_date = 5;
}

message ListSubscriptionsRequest {
    string req_id = 1;
    optional string start_date = 2;
    optional string stop_date = 3;
    optional string user_uuid = 4;
    optional string service_name = 5;

}

message ListSubscriptionsResponse {
    string req_id = 1;
    repeated Subscription subscriptions = 2;
}