version: '3.9'

networks:
  effective_modile:
    driver: bridge


services:

    postgres:
      image: postgres:15
      container_name: ${CONTAINER_POSTGRES_NAME}
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_NAME}
      ports:
        - "${HOST_PORT_FOR_POSTGRES}:${POSTGRES_PORT}"
      volumes:
        - ${DATA_DB_VOLUME_PATH}:/var/lib/postgresql/data
      networks:
        - effective_modile
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        interval: 5s
        timeout: 3s
        retries: 10
        start_period: 10s

    migrations: 
      image: migrate/migrate
      container_name: ${CONTAINER_MIGRATE_NAME}
      depends_on:
        postgres:
          condition: service_healthy
      command:
        - "-path=${VOLUME_PATH_MIGR_ON_CONT}"
        - "-database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB_NAME}?sslmode=disable"
        - "up"
      volumes:
        - ${MIGRATIONS_PATH_ON_HOST}:${VOLUME_PATH_MIGR_ON_CONT}
      restart: on-failure
      networks:
        - effective_modile
    
    controller:
      build:
        context: .
        dockerfile: controller/Dockerfile
      ports:
        - "${CONTROLLER_PORT}:${CONTROLLER_PORT}"
      env_file:
        - .env
      volumes:
        - ./.env:/app/.env:ro
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - effective_modile
    
    endpoint:
      build:
        context: .
        dockerfile: endpoint/Dockerfile
      ports:
        - "${ENDPOINT_PORT}:${ENDPOINT_PORT}"
      env_file:
        - .env
      volumes:
        - ./.env:/app/.env:ro
      networks:
        - effective_modile