version: '3'

tasks:

  sqlc_gen:
    desc: "SQLC кодогенерация"
    dir: ./controller
    cmds:
      - sqlc compile
      - sqlc generate
      
  grpc_gen:
    desc: "PROTOC (gRPC) кодогенерация"
    dir: ./rpc
    cmds:
      - protoc --go_out=./ --go-grpc_out=./ --proto_path=./proto proto/contract.proto
  
  start:
    desc: "start services into docker-compose"
    dir: .
    cmds:
      - docker compose up -d --build

  stop:
    desc: "stope and delete all containers"
    cmds:
      - docker compose down

  restart:
    desc: "restatr all containers"
    cmds:
      - task: stop
      - task: start

